export const DEFAULT_FORMS = {
  destinations: {
    id: '',
    name: '',
    description: '',
    location: '',
    area: '',
    district: '',
    address: '',
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    highlights: [] as string[],
    besttimetovisit: '',
    thingstodo: [] as string[],
    durationtospend: '',
    specialnotice: '',
    entryfee: {},
    averagecostestimate: {},
    openinghours: {},
    howtoreach: '',
    distancefromshillong: '',
    distancefromguwahati: '',
    tags: [] as string[],
    theme: [] as string[],
    visitseason: [] as string[],
    isoffbeat: false,
    isnaturalspot: false,
    ishistorical: false,
    requirespermit: false,
    view_count: 0,
    click_count: 0,
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    sponsoredby: '',
    visibilitystatus: 'visible',
    highlight: false,
    adSlot: 'none',
    adActive: false,
  },
  homestays: {
    id: '',
    name: '',
    description: '',
    location: '',
    area: '',
    address: '',
    district: '',
    distancefromshillong: '',
    distancefromguwahati: '',
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    pricepernight: 0,
    rooms: [] as any[],
    totalrooms: 0,
    checkin_time: '',
    checkout_time: '',
    cancellationpolicy: '',
    house_rules: [] as string[],
    occupancy: 0,
    amenities: [] as string[],
    mealincluded: false,
    priceincludes: [] as string[],
    petfriendly: false,
    wifi: false,
    hasparking: false,
    hasbalcony: false,
    contact: '',
    email: '',
    website: '',
    instant_booking: false,
    availability_status: 'available',
    nearbydestinations: [] as string[],
    nearby_points_of_interest: [] as string[],
    localexperience: [] as string[],
    suitablefor: [] as string[],
    accessibilityfeatures: [] as string[],
    averagecostestimate: {},
    tips: [] as string[],
    warnings: [] as string[],
    tags: [] as string[],
    theme: [] as string[],
    visitseason: [] as string[],
    view_count: 0,
    click_count: 0,
    bookings_count: 0,
    lastbookedat: '',
    isfeaturedforhome: false,
    specialoffers: '',
    popularityindex: 0,
    meta_title: '',
    meta_description: '',
    visibilitystatus: 'visible',
    sponsoredby: '',
    gst_number: '',
    business_type: 'individual',
    adSlot: 'none',
    adActive: false,
  },
  events: {
    id: '',
    name: '',
    description: '',
    location: '',
    area: '',
    district: '',
    address: '',
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    date: '',
    time: '',
    duration: '',
    ismultiday: false,
    isrecurring: false,
    frequency: '',
    season: '',
    visitseason: [] as string[],
    type: '',
    tags: [] as string[],
    theme: [] as string[],
    availablefacilities: [] as string[],
    entryfee: {},
    averagecostestimate: {},
    contact: '',
    email: '',
    website: '',
    organizer: '',
    expectedfootfall: '',
    tips: [] as string[],
    warnings: [] as string[],
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    sponsoredby: '',
    visibilitystatus: 'visible',
    highlight: false,
    adSlot: 'none',
    adActive: false,
  },
  cafes_and_restaurants: {
    id: '',
    name: '',
    description: '',
    location: '',
    area: '',
    district: '',
    address: '',
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    type: '',
    cuisine: [] as string[],
    tags: [] as string[],
    theme: [] as string[],
    visitseason: [] as string[],
    features: [] as string[],
    dietaryoptions: [] as string[],
    accessibility: [] as string[],
    isfamilyfriendly: false,
    menu: [] as string[],
    popularitems: [] as string[],
    pricelevel: '',
    averagecost: 0,
    timing: '',
    season: '',
    isrecurring: false,
    frequency: '',
    distancefromshillong: '',
    distancefromguwahati: '',
    contact: '',
    email: '',
    website: '',
    socialmedia: {},
    tips: [] as string[],
    warnings: [] as string[],
    view_count: 0,
    click_count: 0,
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    visibilitystatus: 'visible',
    highlight: false,
    sponsoredby: '',
    adSlot: 'none',
    adActive: false,
    isfeaturedforhome: false,
  },
  rentals: {
    id: '',
    name: '',
    description: '',
    type: '',
    vehiclefeatures: [] as string[],
    fuelpolicy: [] as string[],
    terms: [] as string[],
    documentsrequired: [] as string[],
    priceperday: 0,
    availability: '',
    location: '',
    district: '',
    distancefromshillong: '',
    distancefromguwahati: '',
    contact: '',
    email: '',
    website: '',
    image: '',
    gallery: [] as string[],
    tags: [] as string[],
    theme: [] as string[],
    suitablefor: [] as string[],
    visitseason: [] as string[],
    averagecostestimate: {},
    tips: [] as string[],
    warnings: [] as string[],
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    visibilitystatus: 'visible',
    highlight: false,
    sponsoredby: '',
    adSlot: 'none',
    adActive: false,
  },
  thrills: {
    id: '',
    name: '',
    description: '',
    location: '',
    district: '',
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    activitytype: '',
    difficultylevel: '',
    safetymeasures: [] as string[],
    season: '',
    visitseason: [] as string[],
    frequency: '',
    tags: [] as string[],
    theme: [] as string[],
    suitablefor: [] as string[],
    accessibility: [] as string[],
    price: 0,
    averagecostestimate: {},
    tips: [] as string[],
    warnings: [] as string[],
    contact: '',
    email: '',
    website: '',
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    sponsoredby: '',
    visibilitystatus: 'visible',
    highlight: false,
    adSlot: 'none',
    adActive: false,
  },
  travel_tips: {
    id: '',
    title: '',
    slug: '',
    content: '',
    category: '',
    tags: [] as string[],
    theme: [] as string[],
    applicability: [] as string[],
    season: '',
    visitseason: [] as string[],
    location: '',
    district: '',
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    source_url: '',
    author: '',
    priority_level: '',
    contact: '',
    email: '',
    website: '',
    socialmedia: {},
    tips: [] as string[],
    warnings: [] as string[],
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    visibilitystatus: 'visible',
    highlight: false,
    sponsoredby: '',
    adSlot: 'none',
    adActive: false,
    isfeaturedforhome: false,
  },
  blogs: {
    id: '',
    title: '',
    slug: '',
    content: '',
    excerpt: '',
    author: '',
    category: '',
    tags: [] as string[],
    theme: [] as string[],
    visitseason: [] as string[],
    image: '',
    gallery: [] as string[],
    media: [] as string[],
    published: false,
    published_at: '',
    meta_title: '',
    meta_description: '',
    popularityindex: 0,
    visibilitystatus: 'visible',
    highlight: false,
    sponsoredby: '',
    adSlot: 'none',
    adActive: false,
  },
  itineraries: {
    id: '',
    title: '',
    slug: '',
    description: '',
    days: 0,
    idealfor: [] as string[],
    theme: [] as string[],
    visitseason: [] as string[],
    tags: [] as string[],
    travelmode: [] as string[],
    regionscovered: [] as string[],
    highlights: [] as string[],
    tips: [] as string[],
    warnings: [] as string[],
    image: '',
    gallery: [] as string[],
    popularityindex: 0,
    meta_title: '',
    meta_description: '',
    visibilitystatus: 'visible',
    sponsoredby: '',
    adSlot: 'none',
    adActive: false,
  },
  prebuilt_faqs: {
    id: '',
    question: '',
    answer: '',
    category: '',
    tags: [] as string[],
    theme: [] as string[],
    audience: [],
    priority: '',
    visibilitystatus: 'visible',
    popularityindex: 0,
    sponsoredby: '',
    adSlot: 'none',
    adActive: false,
  },
} as const;

export type CategoryKey = keyof typeof DEFAULT_FORMS;
