export const FIELD_OPTIONS = {
  homestays: {
    tags: ['budget', 'offbeat', 'heritage', 'eco-friendly'],
    theme: ['Nature stay', 'Luxury retreat', 'Rustic', 'Romantic'],
    visitseason: ['Winter', 'Monsoon', 'Autumn', 'Year-round'],
    amenities: ['WiFi', 'Balcony', 'Power backup', 'Private bathroom'],
    priceincludes: ['Breakfast', 'WiFi', 'Towels', 'Housekeeping'],
    localexperience: ['Village life', 'Waterfall visit', 'Local cuisine', 'Nature walk'],
    suitablefor: ['Family', 'Solo', 'Couples', 'Senior Citizens'],
    accessibilityfeatures: ['Wheelchair Accessible', 'Ground floor room', 'Ramp access', 'Elderly friendly'],
    houserules: ['No smoking', 'No loud music after 10PM', 'Pets allowed', 'Shoes off inside rooms'],
  },
  destinations: {
    tags: ['waterfall', 'offbeat', 'romantic', 'roadtrip'],
    theme: ['Nature', 'Adventure', 'Cultural', 'Hidden Gem'],
    visitseason: ['Winter', 'Monsoon', 'Post-Monsoon', 'All Seasons'],
    entryfeeType: ['Free', 'Paid', 'By Donation', 'By Permit'],
    openingdays: ['All Days', 'Weekends', 'Mon-Sat', 'Seasonal'],
  },
  cafes: {
    type: ['Cafe', 'Fine Dining', 'Street Food', 'Bakery'],
    cuisine: ['Khasi', 'Chinese', 'Continental', 'Tibetan'],
    tags: ['romantic', 'pet-friendly', 'budget', 'wifi'],
    theme: ['Garden', 'Cozy', 'Bohemian', 'Rustic'],
    visitseason: ['Winter', 'Monsoon', 'Festive Season', 'All Seasons'],
    features: ['Rooftop', 'Outdoor seating', 'Live music', 'Power backup'],
    dietaryoptions: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Jain'],
    accessibility: ['Wheelchair Accessible', 'Ramp Access', 'Elderly Friendly', 'Parking Near Entrance'],
  },
  blogs: {
    tags: ['adventure', 'romantic', 'offbeat', 'trekking'],
    theme: ['Budget', 'Cultural', 'Nature', 'Solo Travel'],
    category: ['Hidden Gems', 'Travel Tips', 'Food', 'Weekend Plans'],
  },
  events: {
    type: ['Festival', 'Concert', 'Cultural Show', 'Workshop'],
    tags: ['outdoor', 'cultural', 'food', 'seasonal'],
    theme: ['Cultural', 'Youth', 'Festive', 'Music & Dance'],
    visitseason: ['Winter', 'Spring', 'Festival Season', 'All Seasons'],
    season: ['Winter', 'Summer', 'Festival Season', 'Monsoon'],
    entryfeeType: ['Free', 'Paid', 'Donation', 'Members Only'],
    availablefacilities: ['Parking', 'Food', 'Restroom', 'Security'],
    frequency: ['Annually', 'Monthly', 'Every Weekend', 'One-time'],
  },
  faqs: {
    category: ['Connectivity', 'Travel Rules', 'Safety', 'Weather'],
    tags: ['mobile', 'permit', 'safety', 'road'],
    theme: ['Essentials', 'Safety', 'Backpacking', 'Cultural Etiquette'],
    audience: ['Everyone', 'Solo Travelers', 'Families', 'Foreign Tourists'],
    priority: ['High', 'Medium', 'Low'],
  },
  itineraries: {
    idealfor: ['Backpackers', 'Families', 'Couples', 'Solo Travelers'],
    theme: ['Nature', 'Culture', 'Offbeat', 'Romantic'],
    visitseason: ['Winter', 'Monsoon', 'Spring', 'Year-round'],
    tags: ['3-day', 'Weekend', 'Budget', 'Roadtrip'],
    travelmode: ['Self-drive', 'Taxi', 'Bike Rental', 'Tour Package'],
    regionscovered: [
      'East Khasi Hills',
      'Ri Bhoi',
      'West Jaintia Hills',
      'South Garo Hills',
    ],
  },
  rentals: {
    type: ['Bike', 'Scooter', 'Car', 'SUV'],
    vehiclefeatures: ['Helmet Included', 'GPS', 'Alloy Wheels', 'Mobile Charger'],
    fuelpolicy: [
      'Full to Full',
      'Fuel Extra',
      'No Fuel Included',
      'Half Tank Provided',
    ],
    terms: [
      'Full day rental only',
      'Max 100 km/day',
      'No refund for early return',
      'Drop before 8 PM',
    ],
    documentsrequired: [
      'Driving License',
      'Aadhar',
      'Passport Copy',
      'Student ID',
    ],
    tags: ['Budget', 'Premium', 'Offroad', 'Family'],
    theme: ['Adventure', 'Budget', 'Luxury', 'Solo Travel'],
    suitablefor: ['Solo', 'Couples', 'Families', 'Tourists'],
    visitseason: ['Winter', 'Summer', 'Monsoon', 'Year-round'],
  },
  thrills: {
    activitytype: ['Zipline', 'Caving', 'Kayaking', 'Trekking'],
    difficultylevel: ['Easy', 'Moderate', 'Hard', 'Extreme'],
    safetymeasures: [
      'Helmet',
      'Harness',
      'Life Jacket',
      'Instructor Supervision',
    ],
    season: ['Winter', 'Summer', 'Monsoon', 'Spring'],
    visitseason: ['Year-round', 'Post-Monsoon', 'Spring', 'Summer'],
    frequency: ['Everyday', 'Every weekend', 'Weekly', 'Seasonal'],
    tags: ['Adventure', 'Scenic', 'Offbeat', 'Group'],
    theme: ['Adventure', 'Nature', 'Thrill', 'Offbeat'],
    suitablefor: ['Solo', 'Group', 'Families', 'Students'],
    accessibility: [
      'Wheelchair friendly',
      'Not accessible',
      'Moderate accessibility',
      'Not recommended for elderly',
    ],
  },
  traveltips: {
    category: ['Budget', 'Packing', 'Local Etiquette', 'Travel Safety'],
    tags: ['Budget', 'Safety', 'Packing', 'Food'],
    theme: ['Adventure', 'Family Travel', 'Cultural', 'Eco Travel'],
    applicability: ['Solo', 'Couples', 'Families', 'Senior Citizens'],
    season: ['Winter', 'Summer', 'Monsoon', 'Spring'],
    visitseason: ['Post-Monsoon', 'Festival Season', 'Spring', 'Winter'],
    prioritylevel: ['High', 'Medium', 'Low'],
  },
} as const;

export type FieldOptions = typeof FIELD_OPTIONS;