export const LOCATION_ZONES = [
  'Ampati',
  'Amlarem',
  'Baghmara',
  'Bajengdoba',
  'Chokpot',
  'Dalu',
  'Dawki',
  'Gasuapara',
  'Jowai',
  'Khliehriat',
  'Mairang',
  'Mawkyrwat',
  'Mawphlang',
  'Mawsynram',
  'Mawryngkneng',
  'Mylliem',
  'Nartiang',
  'Nengkhra',
  'Nongjrong',
  'Nongkhlaw',
  'Nongmynsong',
  'Nongstoin',
  'Pynursla',
  'Ranikor',
  'Resubelpara',
  'Ri Bhoi',
  'Rongram',
  'Samanda',
  'Selsella',
  'Shella Bholaganj',
  'Shillong',
  'Sohra (Cherrapunji)',
  'Sohryngkham',
  'Songsak',
  'Tikrikilla',
  'Tura',
  'Williamnagar'
];
export type LocationZone = typeof LOCATION_ZONES[number];
